### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by LiquidAce** [noob-hackers/ighack#6]
Fata error "name='csrftoken', domain=None, path=None"
This error appeared.

**Comment by Bharatrazz** [comment]
fatal error:: Connection to host failed , check your connec
tion and tor configuration :: SOCKSHTTPConnectionPool(host-
'httpbin.org', port=80): Max retries exceeded with url: /ip
(Caused by NewConnectionError("<urllib3.contrib.socks.SOCK
SConnection object at 0x7935785650>: Failed to establish a
new connection: Ox06: TTL expired'))
